// Verified Live Spotify Data Catalog
// All tracks and photos are fetched directly from the Spotify Web API (i.scdn.co)
import { Track, Playlist, Artist } from "@/types/music";

export const SPOTIFY_TRACKS: Track[] = [
  {
    "id": "5MhMXTuVODDF234VDvSxQx",
    "title": "Awake",
    "artist": "Tycho",
    "album": "Awake",
    "duration": 284,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273016e76981b3dfd695b90ff52",
    "genre": "Nocturnal",
    "year": 2014,
    "spotifyId": "5MhMXTuVODDF234VDvSxQx",
    "spotifyUrl": "https://open.spotify.com/track/5MhMXTuVODDF234VDvSxQx",
    "spotifyUri": "spotify:track:5MhMXTuVODDF234VDvSxQx"
  },
  {
    "id": "3rCtueI7qBN2kZBZnXuk5K",
    "title": "Linked",
    "artist": "Bonobo",
    "album": "Linked",
    "duration": 369,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2730e598fe2f3560309382942bb",
    "genre": "Nocturnal",
    "year": 2019,
    "spotifyId": "3rCtueI7qBN2kZBZnXuk5K",
    "spotifyUrl": "https://open.spotify.com/track/3rCtueI7qBN2kZBZnXuk5K",
    "spotifyUri": "spotify:track:3rCtueI7qBN2kZBZnXuk5K"
  },
  {
    "id": "2aJDlirz6v2a4HREki98cP",
    "title": "Glue",
    "artist": "BICEP",
    "album": "Bicep",
    "duration": 269,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273d4322a9004288009f6da2975",
    "genre": "Nocturnal",
    "year": 2017,
    "spotifyId": "2aJDlirz6v2a4HREki98cP",
    "spotifyUrl": "https://open.spotify.com/track/2aJDlirz6v2a4HREki98cP",
    "spotifyUri": "spotify:track:2aJDlirz6v2a4HREki98cP"
  },
  {
    "id": "5S3F5GL8LASIjPg2PMiU1Q",
    "title": "Emerald Rush",
    "artist": "Jon Hopkins",
    "album": "Singularity",
    "duration": 337,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2736e2053350b4f7fd2242bea53",
    "genre": "Nocturnal",
    "year": 2018,
    "spotifyId": "5S3F5GL8LASIjPg2PMiU1Q",
    "spotifyUrl": "https://open.spotify.com/track/5S3F5GL8LASIjPg2PMiU1Q",
    "spotifyUri": "spotify:track:5S3F5GL8LASIjPg2PMiU1Q"
  },
  {
    "id": "5kJ4BWZ9Y1qFIwwTbMIxYX",
    "title": "The Difference",
    "artist": "Flume, Toro y Moi",
    "album": "The Difference",
    "duration": 140,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2735c722571b4538055919b93cc",
    "genre": "Nocturnal",
    "year": 2020,
    "spotifyId": "5kJ4BWZ9Y1qFIwwTbMIxYX",
    "spotifyUrl": "https://open.spotify.com/track/5kJ4BWZ9Y1qFIwwTbMIxYX",
    "spotifyUri": "spotify:track:5kJ4BWZ9Y1qFIwwTbMIxYX"
  },
  {
    "id": "7jZHUhAmW5oq1cq6s8IxmK",
    "title": "Sun Models",
    "artist": "ODESZA, Madelyn Grant",
    "album": "In Return",
    "duration": 160,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273dbd801e562b7a9474ce8bae2",
    "genre": "Nocturnal",
    "year": 2014,
    "spotifyId": "7jZHUhAmW5oq1cq6s8IxmK",
    "spotifyUrl": "https://open.spotify.com/track/7jZHUhAmW5oq1cq6s8IxmK",
    "spotifyUri": "spotify:track:7jZHUhAmW5oq1cq6s8IxmK"
  },
  {
    "id": "24ntSW3QVJzR79lHAAOTaY",
    "title": "Texas Sun",
    "artist": "Khruangbin, Leon Bridges",
    "album": "Texas Sun",
    "duration": 253,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ff26bd277274b27f249cc638",
    "genre": "Sunset",
    "year": 2020,
    "spotifyId": "24ntSW3QVJzR79lHAAOTaY",
    "spotifyUrl": "https://open.spotify.com/track/24ntSW3QVJzR79lHAAOTaY",
    "spotifyUri": "spotify:track:24ntSW3QVJzR79lHAAOTaY"
  },
  {
    "id": "75IQVo8hqI1iwVZyvkN2VT",
    "title": "Show Me How",
    "artist": "Men I Trust",
    "album": "Show Me How",
    "duration": 215,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273deeb617204bc14f4ee87b057",
    "genre": "Sunset",
    "year": 2018,
    "spotifyId": "75IQVo8hqI1iwVZyvkN2VT",
    "spotifyUrl": "https://open.spotify.com/track/75IQVo8hqI1iwVZyvkN2VT",
    "spotifyUri": "spotify:track:75IQVo8hqI1iwVZyvkN2VT"
  },
  {
    "id": "1Snko28yJOihcRVXs9dAo9",
    "title": "Chamber Of Reflection",
    "artist": "Mac DeMarco",
    "album": "Salad Days",
    "duration": 232,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2738b221f2ccf777ae0d4b0db50",
    "genre": "Sunset",
    "year": 2014,
    "spotifyId": "1Snko28yJOihcRVXs9dAo9",
    "spotifyUrl": "https://open.spotify.com/track/1Snko28yJOihcRVXs9dAo9",
    "spotifyUri": "spotify:track:1Snko28yJOihcRVXs9dAo9"
  },
  {
    "id": "1oAwsWBovWRIp7qLMGPIet",
    "title": "Apocalypse",
    "artist": "Cigarettes After Sex",
    "album": "Cigarettes After Sex",
    "duration": 290,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273dfed999f959177dfc4f33cdc",
    "genre": "Sunset",
    "year": 2017,
    "spotifyId": "1oAwsWBovWRIp7qLMGPIet",
    "spotifyUrl": "https://open.spotify.com/track/1oAwsWBovWRIp7qLMGPIet",
    "spotifyUri": "spotify:track:1oAwsWBovWRIp7qLMGPIet"
  },
  {
    "id": "1wicceeNVtcnym2YjiOmyj",
    "title": "Bags",
    "artist": "Clairo",
    "album": "Immunity",
    "duration": 261,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733e4fc846c2b52b9cb6ff2e1f",
    "genre": "Sunset",
    "year": 2019,
    "spotifyId": "1wicceeNVtcnym2YjiOmyj",
    "spotifyUrl": "https://open.spotify.com/track/1wicceeNVtcnym2YjiOmyj",
    "spotifyUri": "spotify:track:1wicceeNVtcnym2YjiOmyj"
  },
  {
    "id": "7eqoqGkKwgOaWNNHx90uEZ",
    "title": "Nights",
    "artist": "Frank Ocean",
    "album": "Blonde",
    "duration": 307,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526",
    "genre": "After Hours",
    "year": 2016,
    "spotifyId": "7eqoqGkKwgOaWNNHx90uEZ",
    "spotifyUrl": "https://open.spotify.com/track/7eqoqGkKwgOaWNNHx90uEZ",
    "spotifyUri": "spotify:track:7eqoqGkKwgOaWNNHx90uEZ"
  },
  {
    "id": "2p8IUWQDrpjuFltbdgLOag",
    "title": "After Hours",
    "artist": "The Weeknd",
    "album": "After Hours",
    "duration": 361,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36",
    "genre": "After Hours",
    "year": 2020,
    "spotifyId": "2p8IUWQDrpjuFltbdgLOag",
    "spotifyUrl": "https://open.spotify.com/track/2p8IUWQDrpjuFltbdgLOag",
    "spotifyUri": "spotify:track:2p8IUWQDrpjuFltbdgLOag"
  },
  {
    "id": "7IVukH71OXfAu3KudrrizN",
    "title": "Japanese Denim",
    "artist": "Daniel Caesar",
    "album": "Get You - Single",
    "duration": 271,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2737465bef53d9e3a27c63c7a1d",
    "genre": "After Hours",
    "year": 2016,
    "spotifyId": "7IVukH71OXfAu3KudrrizN",
    "spotifyUrl": "https://open.spotify.com/track/7IVukH71OXfAu3KudrrizN",
    "spotifyUri": "spotify:track:7IVukH71OXfAu3KudrrizN"
  },
  {
    "id": "4iZ4pt7kvcaH6Yo8UoZ4s2",
    "title": "Snooze",
    "artist": "SZA",
    "album": "SOS",
    "duration": 202,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273bc18bdade69ec5ef0bb25b17",
    "genre": "After Hours",
    "year": 2022,
    "spotifyId": "4iZ4pt7kvcaH6Yo8UoZ4s2",
    "spotifyUrl": "https://open.spotify.com/track/4iZ4pt7kvcaH6Yo8UoZ4s2",
    "spotifyUri": "spotify:track:4iZ4pt7kvcaH6Yo8UoZ4s2"
  },
  {
    "id": "2J6OF7CkpdQGSfm1wdclqn",
    "title": "Clouded",
    "artist": "Brent Faiyaz",
    "album": "Fuck The World",
    "duration": 110,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2736a463f436bbf07f3c9e8c62a",
    "genre": "After Hours",
    "year": 2020,
    "spotifyId": "2J6OF7CkpdQGSfm1wdclqn",
    "spotifyUrl": "https://open.spotify.com/track/2J6OF7CkpdQGSfm1wdclqn",
    "spotifyUri": "spotify:track:2J6OF7CkpdQGSfm1wdclqn"
  },
  {
    "id": "3vQ4T78TTMOjQXGfXVKQJo",
    "title": "Redbone",
    "artist": "Childish Gambino",
    "album": "\"Awaken, My Love!\"",
    "duration": 327,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2731c29562d6e8c1f55bb1311d5",
    "genre": "After Hours",
    "year": 2016,
    "spotifyId": "3vQ4T78TTMOjQXGfXVKQJo",
    "spotifyUrl": "https://open.spotify.com/track/3vQ4T78TTMOjQXGfXVKQJo",
    "spotifyUri": "spotify:track:3vQ4T78TTMOjQXGfXVKQJo"
  },
  {
    "id": "1BncfTJAWxrsxyT9culBrj",
    "title": "Experience",
    "artist": "Ludovico Einaudi, Daniel Hope, I Virtuosi Italiani",
    "album": "In A Time Lapse",
    "duration": 315,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2736c8ef0538e04f2e28380dcc5",
    "genre": "Focus",
    "year": 2013,
    "spotifyId": "1BncfTJAWxrsxyT9culBrj",
    "spotifyUrl": "https://open.spotify.com/track/1BncfTJAWxrsxyT9culBrj",
    "spotifyUri": "spotify:track:1BncfTJAWxrsxyT9culBrj"
  },
  {
    "id": "56oReVXIfUO9xkX7pHmEU0",
    "title": "On the Nature of Daylight",
    "artist": "Max Richter, Louisa Fuller, Natalia Bonner, John Metcalfe, Philip Sheppard, Chris Worsey",
    "album": "The Blue Notebooks (15 Years)",
    "duration": 372,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273e2821b1458ab996fdf2c47ad",
    "genre": "Focus",
    "year": 2018,
    "spotifyId": "56oReVXIfUO9xkX7pHmEU0",
    "spotifyUrl": "https://open.spotify.com/track/56oReVXIfUO9xkX7pHmEU0",
    "spotifyUri": "spotify:track:56oReVXIfUO9xkX7pHmEU0"
  },
  {
    "id": "5626KdflSKfeDK7RJQfSrE",
    "title": "Says",
    "artist": "Nils Frahm",
    "album": "Spaces",
    "duration": 498,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27344beff2f0733508e7284acb3",
    "genre": "Focus",
    "year": 2013,
    "spotifyId": "5626KdflSKfeDK7RJQfSrE",
    "spotifyUrl": "https://open.spotify.com/track/5626KdflSKfeDK7RJQfSrE",
    "spotifyUri": "spotify:track:5626KdflSKfeDK7RJQfSrE"
  },
  {
    "id": "6Xajr512QEGAZ20bqAWkyT",
    "title": "Near Light",
    "artist": "Ólafur Arnalds",
    "album": "Living Room Songs",
    "duration": 209,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273b39434500b17332cd9818487",
    "genre": "Focus",
    "year": 2011,
    "spotifyId": "6Xajr512QEGAZ20bqAWkyT",
    "spotifyUrl": "https://open.spotify.com/track/6Xajr512QEGAZ20bqAWkyT",
    "spotifyUri": "spotify:track:6Xajr512QEGAZ20bqAWkyT"
  },
  {
    "id": "6c7uYlmHJtZPnenPjqG7Ir",
    "title": "Sleeping Lotus",
    "artist": "Joep Beving",
    "album": "Solipsism",
    "duration": 152,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273b61d334e6d7ec597d5cdc38a",
    "genre": "Focus",
    "year": 2015,
    "spotifyId": "6c7uYlmHJtZPnenPjqG7Ir",
    "spotifyUrl": "https://open.spotify.com/track/6c7uYlmHJtZPnenPjqG7Ir",
    "spotifyUri": "spotify:track:6c7uYlmHJtZPnenPjqG7Ir"
  },
  {
    "id": "3Sy6wgTNEp6vSgLs4EyXAf",
    "title": "Flight from the City",
    "artist": "Jóhann Jóhannsson, Yuki Numata Resnick, Tarn Travers, Ben Russell, Clarice Jensen",
    "album": "Orphée",
    "duration": 391,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2738988ae051bcdcab293a76f3d",
    "genre": "Focus",
    "year": 2016,
    "spotifyId": "3Sy6wgTNEp6vSgLs4EyXAf",
    "spotifyUrl": "https://open.spotify.com/track/3Sy6wgTNEp6vSgLs4EyXAf",
    "spotifyUri": "spotify:track:3Sy6wgTNEp6vSgLs4EyXAf"
  },
  {
    "id": "4KROoGIaPaR1pBHPnR3bwC",
    "title": "Pink Moon",
    "artist": "Nick Drake",
    "album": "Pink Moon",
    "duration": 124,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273e369195caf5d169bf5e9eafc",
    "genre": "Morning",
    "year": 1972,
    "spotifyId": "4KROoGIaPaR1pBHPnR3bwC",
    "spotifyUrl": "https://open.spotify.com/track/4KROoGIaPaR1pBHPnR3bwC",
    "spotifyUri": "spotify:track:4KROoGIaPaR1pBHPnR3bwC"
  },
  {
    "id": "6R8agdKCfA4Poo0vnRKQKo",
    "title": "Cayman Islands",
    "artist": "Kings of Convenience",
    "album": "Riot On An Empty Street",
    "duration": 183,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273e9a18c4792e88f34bd17bbaf",
    "genre": "Morning",
    "year": 2004,
    "spotifyId": "6R8agdKCfA4Poo0vnRKQKo",
    "spotifyUrl": "https://open.spotify.com/track/6R8agdKCfA4Poo0vnRKQKo",
    "spotifyUri": "spotify:track:6R8agdKCfA4Poo0vnRKQKo"
  },
  {
    "id": "5ibNaVO251Pb2c0Wdl00gG",
    "title": "Heartbeats",
    "artist": "José González",
    "album": "Veneer",
    "duration": 160,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27376557bf2d3926bf5a607cd92",
    "genre": "Morning",
    "year": 2003,
    "spotifyId": "5ibNaVO251Pb2c0Wdl00gG",
    "spotifyUrl": "https://open.spotify.com/track/5ibNaVO251Pb2c0Wdl00gG",
    "spotifyUri": "spotify:track:5ibNaVO251Pb2c0Wdl00gG"
  },
  {
    "id": "1fEGtTZjrjJW8eUeewnNJR",
    "title": "Flightless Bird, American Mouth",
    "artist": "Iron & Wine",
    "album": "The Shepherd's Dog",
    "duration": 242,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273816243514f01ac30d0932622",
    "genre": "Morning",
    "year": 2007,
    "spotifyId": "1fEGtTZjrjJW8eUeewnNJR",
    "spotifyUrl": "https://open.spotify.com/track/1fEGtTZjrjJW8eUeewnNJR",
    "spotifyUri": "spotify:track:1fEGtTZjrjJW8eUeewnNJR"
  },
  {
    "id": "5GbVzc6Ex5LYlLJqzRQhuy",
    "title": "Mystery of Love",
    "artist": "Sufjan Stevens",
    "album": "Mystery of Love",
    "duration": 249,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733fc1588803d1887f11d660cc",
    "genre": "Morning",
    "year": 2017,
    "spotifyId": "5GbVzc6Ex5LYlLJqzRQhuy",
    "spotifyUrl": "https://open.spotify.com/track/5GbVzc6Ex5LYlLJqzRQhuy",
    "spotifyUri": "spotify:track:5GbVzc6Ex5LYlLJqzRQhuy"
  },
  {
    "id": "35KiiILklye1JRRctaLUb4",
    "title": "Holocene",
    "artist": "Bon Iver",
    "album": "Bon Iver, Bon Iver",
    "duration": 337,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2734b6b1547455bbecb9f6bba64",
    "genre": "Morning",
    "year": 2011,
    "spotifyId": "35KiiILklye1JRRctaLUb4",
    "spotifyUrl": "https://open.spotify.com/track/35KiiILklye1JRRctaLUb4",
    "spotifyUri": "spotify:track:35KiiILklye1JRRctaLUb4"
  },
  {
    "id": "0U0ldCRmgCqhVvD6ksG63j",
    "title": "Nightcall",
    "artist": "Kavinsky",
    "album": "Nightcall",
    "duration": 258,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273d6d8c2eaa1f9031b62f7a3f7",
    "genre": "Drive",
    "year": 2010,
    "spotifyId": "0U0ldCRmgCqhVvD6ksG63j",
    "spotifyUrl": "https://open.spotify.com/track/0U0ldCRmgCqhVvD6ksG63j",
    "spotifyUri": "spotify:track:0U0ldCRmgCqhVvD6ksG63j"
  },
  {
    "id": "5BAJDNTutBFJL27pKunac1",
    "title": "Shadow (Maceo Plex Remix)",
    "artist": "Maceo Plex, Chromatics",
    "album": "Shadow (Remixes)",
    "duration": 299,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27369ff053afe6df53a6a1fda92",
    "genre": "Drive",
    "year": 2021,
    "spotifyId": "5BAJDNTutBFJL27pKunac1",
    "spotifyUrl": "https://open.spotify.com/track/5BAJDNTutBFJL27pKunac1",
    "spotifyUri": "spotify:track:5BAJDNTutBFJL27pKunac1"
  },
  {
    "id": "6mB9A9YLbY4jxpKX5EYAnT",
    "title": "Sunset",
    "artist": "The Midnight",
    "album": "Endless Summer",
    "duration": 327,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27366f27b0ef0b92099a1927721",
    "genre": "Drive",
    "year": 2016,
    "spotifyId": "6mB9A9YLbY4jxpKX5EYAnT",
    "spotifyUrl": "https://open.spotify.com/track/6mB9A9YLbY4jxpKX5EYAnT",
    "spotifyUri": "spotify:track:6mB9A9YLbY4jxpKX5EYAnT"
  },
  {
    "id": "6GyFP1nfCDB8lbD2bG0Hq9",
    "title": "Midnight City",
    "artist": "M83",
    "album": "Hurry up, We're Dreaming",
    "duration": 244,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27362100064780b1d919a95fcf4",
    "genre": "Drive",
    "year": 2011,
    "spotifyId": "6GyFP1nfCDB8lbD2bG0Hq9",
    "spotifyUrl": "https://open.spotify.com/track/6GyFP1nfCDB8lbD2bG0Hq9",
    "spotifyUri": "spotify:track:6GyFP1nfCDB8lbD2bG0Hq9"
  },
  {
    "id": "5VKEsChbUowEF2BT0gJSGX",
    "title": "Tech Noir",
    "artist": "Gunship, John Carpenter, Charlie Simpson",
    "album": "GUNSHIP",
    "duration": 297,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ff61b32d8807c35e7dd09aa7",
    "genre": "Drive",
    "year": 2015,
    "spotifyId": "5VKEsChbUowEF2BT0gJSGX",
    "spotifyUrl": "https://open.spotify.com/track/5VKEsChbUowEF2BT0gJSGX",
    "spotifyUri": "spotify:track:5VKEsChbUowEF2BT0gJSGX"
  },
  {
    "id": "2NHkwSwm6C6eAX3z6xm7Uy",
    "title": "Resonance",
    "artist": "Home",
    "album": "Odyssey",
    "duration": 213,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273df1e0c6802ff4723a425179c",
    "genre": "Drive",
    "year": 2014,
    "spotifyId": "2NHkwSwm6C6eAX3z6xm7Uy",
    "spotifyUrl": "https://open.spotify.com/track/2NHkwSwm6C6eAX3z6xm7Uy",
    "spotifyUri": "spotify:track:2NHkwSwm6C6eAX3z6xm7Uy"
  },
  {
    "id": "5kadOt1O3LrIV46dns9v7u",
    "title": "Archangel",
    "artist": "Burial",
    "album": "Untrue",
    "duration": 240,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2730ea5498497e5bdcdb59a687a",
    "genre": "Future Garage",
    "year": 2007,
    "spotifyId": "5kadOt1O3LrIV46dns9v7u",
    "spotifyUrl": "https://open.spotify.com/track/5kadOt1O3LrIV46dns9v7u",
    "spotifyUri": "spotify:track:5kadOt1O3LrIV46dns9v7u"
  },
  {
    "id": "1YGxSgWIWqxKuLLocPVxhC",
    "title": "So U Kno",
    "artist": "Overmono",
    "album": "Good Lies",
    "duration": 344,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273dd8fbf4e3c304f6b3602a745",
    "genre": "Future Garage",
    "year": 2023,
    "spotifyId": "1YGxSgWIWqxKuLLocPVxhC",
    "spotifyUrl": "https://open.spotify.com/track/1YGxSgWIWqxKuLLocPVxhC",
    "spotifyUri": "spotify:track:1YGxSgWIWqxKuLLocPVxhC"
  },
  {
    "id": "4Z4i631BesV0P6LTvfLAdL",
    "title": "Talk to Me You'll Understand",
    "artist": "Ross from Friends",
    "album": "You'll Understand",
    "duration": 417,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273088d99c85e6de4f30b39679c",
    "genre": "Future Garage",
    "year": 2017,
    "spotifyId": "4Z4i631BesV0P6LTvfLAdL",
    "spotifyUrl": "https://open.spotify.com/track/4Z4i631BesV0P6LTvfLAdL",
    "spotifyUri": "spotify:track:4Z4i631BesV0P6LTvfLAdL"
  },
  {
    "id": "79Jl8KMvmnXedTjjW6pJan",
    "title": "Gosh",
    "artist": "Jamie xx, MC Moose",
    "album": "In Colour",
    "duration": 291,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733b104b3cfcf52e380e90254d",
    "genre": "Future Garage",
    "year": 2015,
    "spotifyId": "79Jl8KMvmnXedTjjW6pJan",
    "spotifyUrl": "https://open.spotify.com/track/79Jl8KMvmnXedTjjW6pJan",
    "spotifyUri": "spotify:track:79Jl8KMvmnXedTjjW6pJan"
  },
  {
    "id": "0uKrhHBDUQ4w5fv4qwOubP",
    "title": "Breathe",
    "artist": "Télépopmusik, Angela McCluskey",
    "album": "Genetic World",
    "duration": 282,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c65b1f9d6ca322de8b85c505",
    "genre": "Future Garage",
    "year": 2001,
    "spotifyId": "0uKrhHBDUQ4w5fv4qwOubP",
    "spotifyUrl": "https://open.spotify.com/track/0uKrhHBDUQ4w5fv4qwOubP",
    "spotifyUri": "spotify:track:0uKrhHBDUQ4w5fv4qwOubP"
  },
  {
    "id": "07eGxuz8bL6QMsRqEe1Adu",
    "title": "Svefn-g-englar",
    "artist": "Sigur Rós",
    "album": "Ágætis byrjun",
    "duration": 607,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2737d5c9fa537845b71c4eb3b5e",
    "genre": "Nordic",
    "year": 1999,
    "spotifyId": "07eGxuz8bL6QMsRqEe1Adu",
    "spotifyUrl": "https://open.spotify.com/track/07eGxuz8bL6QMsRqEe1Adu",
    "spotifyUri": "spotify:track:07eGxuz8bL6QMsRqEe1Adu"
  },
  {
    "id": "7iHl6LcHD94l5VpmfrBUmG",
    "title": "Riverside",
    "artist": "Agnes Obel",
    "album": "Philharmonics",
    "duration": 229,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ae70ffe7505b2a4f45372cb5",
    "genre": "Nordic",
    "year": 2010,
    "spotifyId": "7iHl6LcHD94l5VpmfrBUmG",
    "spotifyUrl": "https://open.spotify.com/track/7iHl6LcHD94l5VpmfrBUmG",
    "spotifyUri": "spotify:track:7iHl6LcHD94l5VpmfrBUmG"
  },
  {
    "id": "2bB6iDVgm25WkYv0yBz1BD",
    "title": "Looped",
    "artist": "Kiasmos",
    "album": "Kiasmos",
    "duration": 361,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273bb0ea18476f664df4f9fd460",
    "genre": "Nordic",
    "year": 2014,
    "spotifyId": "2bB6iDVgm25WkYv0yBz1BD",
    "spotifyUrl": "https://open.spotify.com/track/2bB6iDVgm25WkYv0yBz1BD",
    "spotifyUri": "spotify:track:2bB6iDVgm25WkYv0yBz1BD"
  },
  {
    "id": "6XmY3xNVGemozNMApOCobZ",
    "title": "Pastoral",
    "artist": "Christian Löffler",
    "album": "Parallels: Shellac Reworks By Christian Löffler",
    "duration": 221,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2732ae3934450a9b0c4d9e5c3d3",
    "genre": "Nordic",
    "year": 2021,
    "spotifyId": "6XmY3xNVGemozNMApOCobZ",
    "spotifyUrl": "https://open.spotify.com/track/6XmY3xNVGemozNMApOCobZ",
    "spotifyUri": "spotify:track:6XmY3xNVGemozNMApOCobZ"
  },
  {
    "id": "6eTGxxQxiTFE6LfZHC33Wm",
    "title": "Hoppípolla",
    "artist": "Sigur Rós",
    "album": "Takk...",
    "duration": 269,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ddd29279ec01511dca4c441c",
    "genre": "Nordic",
    "year": 2005,
    "spotifyId": "6eTGxxQxiTFE6LfZHC33Wm",
    "spotifyUrl": "https://open.spotify.com/track/6eTGxxQxiTFE6LfZHC33Wm",
    "spotifyUri": "spotify:track:6eTGxxQxiTFE6LfZHC33Wm"
  },
  {
    "id": "2wA8cQwmSw0eVVhOfNRDuZ",
    "title": "The Sun's Gone Dim and the Sky's Turned Black",
    "artist": "Jóhann Jóhannsson",
    "album": "The Sun's Gone Dim and the Sky's Turned Black",
    "duration": 341,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2737cc2afdaef2df15024915675",
    "genre": "Nordic",
    "year": 2006,
    "spotifyId": "2wA8cQwmSw0eVVhOfNRDuZ",
    "spotifyUrl": "https://open.spotify.com/track/2wA8cQwmSw0eVVhOfNRDuZ",
    "spotifyUri": "spotify:track:2wA8cQwmSw0eVVhOfNRDuZ"
  },
  {
    "id": "6fjC14MDp2hgMiHNfuiexj",
    "title": "Dorado Valley",
    "artist": "Hermanos Gutiérrez",
    "album": "El Bueno Y El Malo",
    "duration": 207,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c0c54c6de30010265e23c840",
    "genre": "Desert Rock",
    "year": 2022,
    "spotifyId": "6fjC14MDp2hgMiHNfuiexj",
    "spotifyUrl": "https://open.spotify.com/track/6fjC14MDp2hgMiHNfuiexj",
    "spotifyUri": "spotify:track:6fjC14MDp2hgMiHNfuiexj"
  },
  {
    "id": "4H0KLsPpr5atperrHGfz3x",
    "title": "Catamaran",
    "artist": "Allah-Las",
    "album": "Allah-Las",
    "duration": 213,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273db27283ab2ae5eddb265d9a7",
    "genre": "Desert Rock",
    "year": 2012,
    "spotifyId": "4H0KLsPpr5atperrHGfz3x",
    "spotifyUrl": "https://open.spotify.com/track/4H0KLsPpr5atperrHGfz3x",
    "spotifyUri": "spotify:track:4H0KLsPpr5atperrHGfz3x"
  },
  {
    "id": "6galGfTFHHzsPieYkReYyN",
    "title": "Organism",
    "artist": "Tommy Guerrero",
    "album": "Soul Food Taqueria",
    "duration": 248,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c27b61aaedf74586b118e34a",
    "genre": "Desert Rock",
    "year": 2002,
    "spotifyId": "6galGfTFHHzsPieYkReYyN",
    "spotifyUrl": "https://open.spotify.com/track/6galGfTFHHzsPieYkReYyN",
    "spotifyUri": "spotify:track:6galGfTFHHzsPieYkReYyN"
  },
  {
    "id": "2dXs6WlSVXJX3i99Xw4n2u",
    "title": "Don't Call My Name",
    "artist": "Skinshape",
    "album": "Life & Love",
    "duration": 250,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27355832e9fb94c657e6e94cb2d",
    "genre": "Desert Rock",
    "year": 2017,
    "spotifyId": "2dXs6WlSVXJX3i99Xw4n2u",
    "spotifyUrl": "https://open.spotify.com/track/2dXs6WlSVXJX3i99Xw4n2u",
    "spotifyUri": "spotify:track:2dXs6WlSVXJX3i99Xw4n2u"
  },
  {
    "id": "5EvSpCCDpZOJvFwr4ZWSk0",
    "title": "Maria También",
    "artist": "Khruangbin",
    "album": "Con Todo El Mundo",
    "duration": 191,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273f8bfa2a86764fc18a80d382e",
    "genre": "Desert Rock",
    "year": 2018,
    "spotifyId": "5EvSpCCDpZOJvFwr4ZWSk0",
    "spotifyUrl": "https://open.spotify.com/track/5EvSpCCDpZOJvFwr4ZWSk0",
    "spotifyUri": "spotify:track:5EvSpCCDpZOJvFwr4ZWSk0"
  },
  {
    "id": "52Bg6oaos7twR7IUtEpqcE",
    "title": "Between The Bars",
    "artist": "Elliott Smith",
    "album": "Either/Or",
    "duration": 141,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ea7ac80765aa4549d18a27b9",
    "genre": "Solo Guitar",
    "year": 1997,
    "spotifyId": "52Bg6oaos7twR7IUtEpqcE",
    "spotifyUrl": "https://open.spotify.com/track/52Bg6oaos7twR7IUtEpqcE",
    "spotifyUri": "spotify:track:52Bg6oaos7twR7IUtEpqcE"
  },
  {
    "id": "5yyRH93h4Pm6tXXYTxt7ea",
    "title": "The Blower's Daughter",
    "artist": "Damien Rice",
    "album": "O",
    "duration": 287,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273fbf054cdb847f4e042d88642",
    "genre": "Solo Guitar",
    "year": 2002,
    "spotifyId": "5yyRH93h4Pm6tXXYTxt7ea",
    "spotifyUrl": "https://open.spotify.com/track/5yyRH93h4Pm6tXXYTxt7ea",
    "spotifyUri": "spotify:track:5yyRH93h4Pm6tXXYTxt7ea"
  },
  {
    "id": "4PwWESSlTwzvw9B7bmtTLS",
    "title": "anything",
    "artist": "Adrianne Lenker",
    "album": "songs",
    "duration": 202,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2738ebe185fc4824bc6e568b511",
    "genre": "Solo Guitar",
    "year": 2020,
    "spotifyId": "4PwWESSlTwzvw9B7bmtTLS",
    "spotifyUrl": "https://open.spotify.com/track/4PwWESSlTwzvw9B7bmtTLS",
    "spotifyUri": "spotify:track:4PwWESSlTwzvw9B7bmtTLS"
  },
  {
    "id": "3B3eOgLJSqPEA0RfboIQVM",
    "title": "Skinny Love",
    "artist": "Bon Iver",
    "album": "For Emma, Forever Ago",
    "duration": 239,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273bf7c317a63c4f128b8823406",
    "genre": "Solo Guitar",
    "year": 2008,
    "spotifyId": "3B3eOgLJSqPEA0RfboIQVM",
    "spotifyUrl": "https://open.spotify.com/track/3B3eOgLJSqPEA0RfboIQVM",
    "spotifyUri": "spotify:track:3B3eOgLJSqPEA0RfboIQVM"
  },
  {
    "id": "5Qnrgqy1pAm9GyNQOgyVFz",
    "title": "Fourth of July",
    "artist": "Sufjan Stevens",
    "album": "Carrie & Lowell",
    "duration": 279,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273820e2ac14772ae3162c6d479",
    "genre": "Solo Guitar",
    "year": 2015,
    "spotifyId": "5Qnrgqy1pAm9GyNQOgyVFz",
    "spotifyUrl": "https://open.spotify.com/track/5Qnrgqy1pAm9GyNQOgyVFz",
    "spotifyUri": "spotify:track:5Qnrgqy1pAm9GyNQOgyVFz"
  },
  {
    "id": "4LGF2tDg3878bs0mQPByZ4",
    "title": "Guaranteed",
    "artist": "Eddie Vedder",
    "album": "Into The Wild (Music For The Motion Picture)",
    "duration": 165,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733ed52339ae78ac1b695e8d80",
    "genre": "Solo Guitar",
    "year": 2007,
    "spotifyId": "4LGF2tDg3878bs0mQPByZ4",
    "spotifyUrl": "https://open.spotify.com/track/4LGF2tDg3878bs0mQPByZ4",
    "spotifyUri": "spotify:track:4LGF2tDg3878bs0mQPByZ4"
  },
  {
    "id": "0vp09QgBhShrQOL2w7P8k4",
    "title": "Recovery",
    "artist": "Rival Consoles",
    "album": "Odyssey / Sonne",
    "duration": 290,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273cf2e55988066ba69d58245ff",
    "genre": "Modular Synth",
    "year": 2015,
    "spotifyId": "0vp09QgBhShrQOL2w7P8k4",
    "spotifyUrl": "https://open.spotify.com/track/0vp09QgBhShrQOL2w7P8k4",
    "spotifyUri": "spotify:track:0vp09QgBhShrQOL2w7P8k4"
  },
  {
    "id": "75QdM3nsnAluOD19G1J4il",
    "title": "Bias",
    "artist": "Floating Points",
    "album": "Crush",
    "duration": 308,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273216a393a7606aa7de52c4636",
    "genre": "Modular Synth",
    "year": 2019,
    "spotifyId": "75QdM3nsnAluOD19G1J4il",
    "spotifyUrl": "https://open.spotify.com/track/75QdM3nsnAluOD19G1J4il",
    "spotifyUri": "spotify:track:75QdM3nsnAluOD19G1J4il"
  },
  {
    "id": "2ZIaH69kaz55RM4Pjx6KXl",
    "title": "Two Thousand and Seventeen",
    "artist": "Four Tet",
    "album": "New Energy",
    "duration": 252,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733f31769b727102837cb32a63",
    "genre": "Modular Synth",
    "year": 2017,
    "spotifyId": "2ZIaH69kaz55RM4Pjx6KXl",
    "spotifyUrl": "https://open.spotify.com/track/2ZIaH69kaz55RM4Pjx6KXl",
    "spotifyUri": "spotify:track:2ZIaH69kaz55RM4Pjx6KXl"
  },
  {
    "id": "3bCmDqflFBHijgJfvtqev5",
    "title": "1/1 - Remastered 2004",
    "artist": "Brian Eno",
    "album": "Ambient 1: Music For Airports (Remastered 2004)",
    "duration": 1042,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27337a379ca6520eaf191de6ff2",
    "genre": "Masterpieces",
    "year": 1978,
    "spotifyId": "3bCmDqflFBHijgJfvtqev5",
    "spotifyUrl": "https://open.spotify.com/track/3bCmDqflFBHijgJfvtqev5",
    "spotifyUri": "spotify:track:3bCmDqflFBHijgJfvtqev5"
  },
  {
    "id": "1uaGSDFsLdReQgg8p7Obwh",
    "title": "Avril 14th",
    "artist": "Aphex Twin",
    "album": "Drukqs",
    "duration": 126,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2732f175ac7dee768cefd14a01c",
    "genre": "Masterpieces",
    "year": 2001,
    "spotifyId": "1uaGSDFsLdReQgg8p7Obwh",
    "spotifyUrl": "https://open.spotify.com/track/1uaGSDFsLdReQgg8p7Obwh",
    "spotifyUri": "spotify:track:1uaGSDFsLdReQgg8p7Obwh"
  },
  {
    "id": "5Hf2h59YLInKlic7ooWZVd",
    "title": "Roygbiv",
    "artist": "Boards of Canada",
    "album": "Music Has The Right To Children",
    "duration": 149,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2739effb26eea559ce6f3fed751",
    "genre": "Masterpieces",
    "year": 1998,
    "spotifyId": "5Hf2h59YLInKlic7ooWZVd",
    "spotifyUrl": "https://open.spotify.com/track/5Hf2h59YLInKlic7ooWZVd",
    "spotifyUri": "spotify:track:5Hf2h59YLInKlic7ooWZVd"
  },
  {
    "id": "67Hna13dNDkZvBpTXRIaOJ",
    "title": "Teardrop",
    "artist": "Massive Attack, Elizabeth Fraser",
    "album": "Mezzanine",
    "duration": 331,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2732fcb0a3c7a66e516b11cd26e",
    "genre": "Masterpieces",
    "year": 1998,
    "spotifyId": "67Hna13dNDkZvBpTXRIaOJ",
    "spotifyUrl": "https://open.spotify.com/track/67Hna13dNDkZvBpTXRIaOJ",
    "spotifyUri": "spotify:track:67Hna13dNDkZvBpTXRIaOJ"
  },
  {
    "id": "3Ty7OTBNSigGEpeW2PqcsC",
    "title": "Glory Box",
    "artist": "Portishead",
    "album": "Dummy",
    "duration": 309,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273dc20397b139223620af148f6",
    "genre": "Masterpieces",
    "year": 1994,
    "spotifyId": "3Ty7OTBNSigGEpeW2PqcsC",
    "spotifyUrl": "https://open.spotify.com/track/3Ty7OTBNSigGEpeW2PqcsC",
    "spotifyUri": "spotify:track:3Ty7OTBNSigGEpeW2PqcsC"
  },
  {
    "id": "409z4jUHpq7eIkg3N3FzZh",
    "title": "Windowlicker",
    "artist": "Aphex Twin",
    "album": "Windowlicker",
    "duration": 366,
    "audioUrl": "",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273478bfd5562acad46103b858a",
    "genre": "Masterpieces",
    "year": 1999,
    "spotifyId": "409z4jUHpq7eIkg3N3FzZh",
    "spotifyUrl": "https://open.spotify.com/track/409z4jUHpq7eIkg3N3FzZh",
    "spotifyUri": "spotify:track:409z4jUHpq7eIkg3N3FzZh"
  }
];

export const SPOTIFY_PLAYLISTS: Playlist[] = [
  {
    "id": "late-night-frequencies",
    "title": "Late Night Frequencies",
    "subtitle": "Nocturnal electronica, ambient textures, and subtle breakbeats.",
    "description": "A deep sequence of analog synth textures, warm sub-bass, and unhurried rhythms. Designed for solitary late-hour flow, creative coding, and night walks.",
    "curator": "Soren Vance",
    "curatorRole": "Sound Curator",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5eb1d2c676997fffa6c04f982cf",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273016e76981b3dfd695b90ff52",
    "accentColor": "#1d192b",
    "category": "late-night",
    "tracks": [
      {
        "id": "5MhMXTuVODDF234VDvSxQx",
        "title": "Awake",
        "artist": "Tycho",
        "album": "Awake",
        "duration": 284,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273016e76981b3dfd695b90ff52",
        "genre": "Nocturnal",
        "year": 2014,
        "spotifyId": "5MhMXTuVODDF234VDvSxQx",
        "spotifyUrl": "https://open.spotify.com/track/5MhMXTuVODDF234VDvSxQx",
        "spotifyUri": "spotify:track:5MhMXTuVODDF234VDvSxQx"
      },
      {
        "id": "3rCtueI7qBN2kZBZnXuk5K",
        "title": "Linked",
        "artist": "Bonobo",
        "album": "Linked",
        "duration": 369,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2730e598fe2f3560309382942bb",
        "genre": "Nocturnal",
        "year": 2019,
        "spotifyId": "3rCtueI7qBN2kZBZnXuk5K",
        "spotifyUrl": "https://open.spotify.com/track/3rCtueI7qBN2kZBZnXuk5K",
        "spotifyUri": "spotify:track:3rCtueI7qBN2kZBZnXuk5K"
      },
      {
        "id": "2aJDlirz6v2a4HREki98cP",
        "title": "Glue",
        "artist": "BICEP",
        "album": "Bicep",
        "duration": 269,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273d4322a9004288009f6da2975",
        "genre": "Nocturnal",
        "year": 2017,
        "spotifyId": "2aJDlirz6v2a4HREki98cP",
        "spotifyUrl": "https://open.spotify.com/track/2aJDlirz6v2a4HREki98cP",
        "spotifyUri": "spotify:track:2aJDlirz6v2a4HREki98cP"
      },
      {
        "id": "5S3F5GL8LASIjPg2PMiU1Q",
        "title": "Emerald Rush",
        "artist": "Jon Hopkins",
        "album": "Singularity",
        "duration": 337,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2736e2053350b4f7fd2242bea53",
        "genre": "Nocturnal",
        "year": 2018,
        "spotifyId": "5S3F5GL8LASIjPg2PMiU1Q",
        "spotifyUrl": "https://open.spotify.com/track/5S3F5GL8LASIjPg2PMiU1Q",
        "spotifyUri": "spotify:track:5S3F5GL8LASIjPg2PMiU1Q"
      },
      {
        "id": "5kJ4BWZ9Y1qFIwwTbMIxYX",
        "title": "The Difference",
        "artist": "Flume, Toro y Moi",
        "album": "The Difference",
        "duration": 140,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2735c722571b4538055919b93cc",
        "genre": "Nocturnal",
        "year": 2020,
        "spotifyId": "5kJ4BWZ9Y1qFIwwTbMIxYX",
        "spotifyUrl": "https://open.spotify.com/track/5kJ4BWZ9Y1qFIwwTbMIxYX",
        "spotifyUri": "spotify:track:5kJ4BWZ9Y1qFIwwTbMIxYX"
      },
      {
        "id": "7jZHUhAmW5oq1cq6s8IxmK",
        "title": "Sun Models",
        "artist": "ODESZA, Madelyn Grant",
        "album": "In Return",
        "duration": 160,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273dbd801e562b7a9474ce8bae2",
        "genre": "Nocturnal",
        "year": 2014,
        "spotifyId": "7jZHUhAmW5oq1cq6s8IxmK",
        "spotifyUrl": "https://open.spotify.com/track/7jZHUhAmW5oq1cq6s8IxmK",
        "spotifyUri": "spotify:track:7jZHUhAmW5oq1cq6s8IxmK"
      }
    ],
    "followersCount": 18164,
    "releaseDate": "2024 Archive",
    "tags": [
      "Nocturnal",
      "Downtempo",
      "Analog Synth",
      "Deep Bass"
    ],
    "spotifyId": "5MhMXTuVODDF234VDvSxQx",
    "spotifyUrl": "https://open.spotify.com/search/Late%20Night%20Frequencies",
    "spotifyUri": "spotify:search:Late%20Night%20Frequencies"
  },
  {
    "id": "golden-hour",
    "title": "Golden Hour",
    "subtitle": "Warm indie-folk, dusk acoustics, and unhurried vocals.",
    "description": "Recorded between the quiet hours of sundown and dusk. Analog tape warmth, acoustic guitars, and serene melodies that soothe the room.",
    "curator": "Elena Rostova",
    "curatorRole": "Acoustic Lead",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5eb80ee1b49f757f4955c47796d",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ff26bd277274b27f249cc638",
    "accentColor": "#2b2114",
    "category": "discover",
    "tracks": [
      {
        "id": "24ntSW3QVJzR79lHAAOTaY",
        "title": "Texas Sun",
        "artist": "Khruangbin, Leon Bridges",
        "album": "Texas Sun",
        "duration": 253,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ff26bd277274b27f249cc638",
        "genre": "Sunset",
        "year": 2020,
        "spotifyId": "24ntSW3QVJzR79lHAAOTaY",
        "spotifyUrl": "https://open.spotify.com/track/24ntSW3QVJzR79lHAAOTaY",
        "spotifyUri": "spotify:track:24ntSW3QVJzR79lHAAOTaY"
      },
      {
        "id": "75IQVo8hqI1iwVZyvkN2VT",
        "title": "Show Me How",
        "artist": "Men I Trust",
        "album": "Show Me How",
        "duration": 215,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273deeb617204bc14f4ee87b057",
        "genre": "Sunset",
        "year": 2018,
        "spotifyId": "75IQVo8hqI1iwVZyvkN2VT",
        "spotifyUrl": "https://open.spotify.com/track/75IQVo8hqI1iwVZyvkN2VT",
        "spotifyUri": "spotify:track:75IQVo8hqI1iwVZyvkN2VT"
      },
      {
        "id": "24ntSW3QVJzR79lHAAOTaY",
        "title": "Texas Sun",
        "artist": "Khruangbin, Leon Bridges",
        "album": "Texas Sun",
        "duration": 253,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ff26bd277274b27f249cc638",
        "genre": "Sunset",
        "year": 2020,
        "spotifyId": "24ntSW3QVJzR79lHAAOTaY",
        "spotifyUrl": "https://open.spotify.com/track/24ntSW3QVJzR79lHAAOTaY",
        "spotifyUri": "spotify:track:24ntSW3QVJzR79lHAAOTaY"
      },
      {
        "id": "1Snko28yJOihcRVXs9dAo9",
        "title": "Chamber Of Reflection",
        "artist": "Mac DeMarco",
        "album": "Salad Days",
        "duration": 232,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2738b221f2ccf777ae0d4b0db50",
        "genre": "Sunset",
        "year": 2014,
        "spotifyId": "1Snko28yJOihcRVXs9dAo9",
        "spotifyUrl": "https://open.spotify.com/track/1Snko28yJOihcRVXs9dAo9",
        "spotifyUri": "spotify:track:1Snko28yJOihcRVXs9dAo9"
      },
      {
        "id": "1oAwsWBovWRIp7qLMGPIet",
        "title": "Apocalypse",
        "artist": "Cigarettes After Sex",
        "album": "Cigarettes After Sex",
        "duration": 290,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273dfed999f959177dfc4f33cdc",
        "genre": "Sunset",
        "year": 2017,
        "spotifyId": "1oAwsWBovWRIp7qLMGPIet",
        "spotifyUrl": "https://open.spotify.com/track/1oAwsWBovWRIp7qLMGPIet",
        "spotifyUri": "spotify:track:1oAwsWBovWRIp7qLMGPIet"
      },
      {
        "id": "1wicceeNVtcnym2YjiOmyj",
        "title": "Bags",
        "artist": "Clairo",
        "album": "Immunity",
        "duration": 261,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733e4fc846c2b52b9cb6ff2e1f",
        "genre": "Sunset",
        "year": 2019,
        "spotifyId": "1wicceeNVtcnym2YjiOmyj",
        "spotifyUrl": "https://open.spotify.com/track/1wicceeNVtcnym2YjiOmyj",
        "spotifyUri": "spotify:track:1wicceeNVtcnym2YjiOmyj"
      }
    ],
    "followersCount": 5285,
    "releaseDate": "2024 Archive",
    "tags": [
      "Sunset",
      "Indie Folk",
      "Acoustic",
      "Warmth"
    ],
    "spotifyId": "24ntSW3QVJzR79lHAAOTaY",
    "spotifyUrl": "https://open.spotify.com/search/Golden%20Hour",
    "spotifyUri": "spotify:search:Golden%20Hour"
  },
  {
    "id": "after-hours",
    "title": "After Hours",
    "subtitle": "Smoky nocturnal R&B, late-night bass, and Rhodes chords.",
    "description": "Subterranean grooves for the hours between 2 AM and sunrise. Heavy low-end, intimate vocal harmonies, and slow-burning percussion.",
    "curator": "Marcus Thorne",
    "curatorRole": "Nocturnal Selector",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5ebd76ddb487b3fc4abec1e550e",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526",
    "accentColor": "#1f142b",
    "category": "late-night",
    "tracks": [
      {
        "id": "7eqoqGkKwgOaWNNHx90uEZ",
        "title": "Nights",
        "artist": "Frank Ocean",
        "album": "Blonde",
        "duration": 307,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526",
        "genre": "After Hours",
        "year": 2016,
        "spotifyId": "7eqoqGkKwgOaWNNHx90uEZ",
        "spotifyUrl": "https://open.spotify.com/track/7eqoqGkKwgOaWNNHx90uEZ",
        "spotifyUri": "spotify:track:7eqoqGkKwgOaWNNHx90uEZ"
      },
      {
        "id": "2p8IUWQDrpjuFltbdgLOag",
        "title": "After Hours",
        "artist": "The Weeknd",
        "album": "After Hours",
        "duration": 361,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36",
        "genre": "After Hours",
        "year": 2020,
        "spotifyId": "2p8IUWQDrpjuFltbdgLOag",
        "spotifyUrl": "https://open.spotify.com/track/2p8IUWQDrpjuFltbdgLOag",
        "spotifyUri": "spotify:track:2p8IUWQDrpjuFltbdgLOag"
      },
      {
        "id": "7IVukH71OXfAu3KudrrizN",
        "title": "Japanese Denim",
        "artist": "Daniel Caesar",
        "album": "Get You - Single",
        "duration": 271,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2737465bef53d9e3a27c63c7a1d",
        "genre": "After Hours",
        "year": 2016,
        "spotifyId": "7IVukH71OXfAu3KudrrizN",
        "spotifyUrl": "https://open.spotify.com/track/7IVukH71OXfAu3KudrrizN",
        "spotifyUri": "spotify:track:7IVukH71OXfAu3KudrrizN"
      },
      {
        "id": "4iZ4pt7kvcaH6Yo8UoZ4s2",
        "title": "Snooze",
        "artist": "SZA",
        "album": "SOS",
        "duration": 202,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273bc18bdade69ec5ef0bb25b17",
        "genre": "After Hours",
        "year": 2022,
        "spotifyId": "4iZ4pt7kvcaH6Yo8UoZ4s2",
        "spotifyUrl": "https://open.spotify.com/track/4iZ4pt7kvcaH6Yo8UoZ4s2",
        "spotifyUri": "spotify:track:4iZ4pt7kvcaH6Yo8UoZ4s2"
      },
      {
        "id": "2J6OF7CkpdQGSfm1wdclqn",
        "title": "Clouded",
        "artist": "Brent Faiyaz",
        "album": "Fuck The World",
        "duration": 110,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2736a463f436bbf07f3c9e8c62a",
        "genre": "After Hours",
        "year": 2020,
        "spotifyId": "2J6OF7CkpdQGSfm1wdclqn",
        "spotifyUrl": "https://open.spotify.com/track/2J6OF7CkpdQGSfm1wdclqn",
        "spotifyUri": "spotify:track:2J6OF7CkpdQGSfm1wdclqn"
      },
      {
        "id": "3vQ4T78TTMOjQXGfXVKQJo",
        "title": "Redbone",
        "artist": "Childish Gambino",
        "album": "\"Awaken, My Love!\"",
        "duration": 327,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2731c29562d6e8c1f55bb1311d5",
        "genre": "After Hours",
        "year": 2016,
        "spotifyId": "3vQ4T78TTMOjQXGfXVKQJo",
        "spotifyUrl": "https://open.spotify.com/track/3vQ4T78TTMOjQXGfXVKQJo",
        "spotifyUri": "spotify:track:3vQ4T78TTMOjQXGfXVKQJo"
      }
    ],
    "followersCount": 21315,
    "releaseDate": "2024 Archive",
    "tags": [
      "After Hours",
      "R&B",
      "Sub Bass",
      "Smoky"
    ],
    "spotifyId": "7eqoqGkKwgOaWNNHx90uEZ",
    "spotifyUrl": "https://open.spotify.com/search/After%20Hours",
    "spotifyUri": "spotify:search:After%20Hours"
  },
  {
    "id": "deep-focus",
    "title": "Deep Focus",
    "subtitle": "Neoclassical strings, modular arpeggios, and felt pianos.",
    "description": "A continuous stream of thought-provoking, non-intrusive sound architecture. Designed to eliminate cognitive distraction and induce flow.",
    "curator": "Julian Kestrel",
    "curatorRole": "Neoclassical Curator",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5eb74b33a0594f71fb3d2f2549e",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2736c8ef0538e04f2e28380dcc5",
    "accentColor": "#14202b",
    "category": "focus",
    "tracks": [
      {
        "id": "1BncfTJAWxrsxyT9culBrj",
        "title": "Experience",
        "artist": "Ludovico Einaudi, Daniel Hope, I Virtuosi Italiani",
        "album": "In A Time Lapse",
        "duration": 315,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2736c8ef0538e04f2e28380dcc5",
        "genre": "Focus",
        "year": 2013,
        "spotifyId": "1BncfTJAWxrsxyT9culBrj",
        "spotifyUrl": "https://open.spotify.com/track/1BncfTJAWxrsxyT9culBrj",
        "spotifyUri": "spotify:track:1BncfTJAWxrsxyT9culBrj"
      },
      {
        "id": "56oReVXIfUO9xkX7pHmEU0",
        "title": "On the Nature of Daylight",
        "artist": "Max Richter, Louisa Fuller, Natalia Bonner, John Metcalfe, Philip Sheppard, Chris Worsey",
        "album": "The Blue Notebooks (15 Years)",
        "duration": 372,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273e2821b1458ab996fdf2c47ad",
        "genre": "Focus",
        "year": 2018,
        "spotifyId": "56oReVXIfUO9xkX7pHmEU0",
        "spotifyUrl": "https://open.spotify.com/track/56oReVXIfUO9xkX7pHmEU0",
        "spotifyUri": "spotify:track:56oReVXIfUO9xkX7pHmEU0"
      },
      {
        "id": "5626KdflSKfeDK7RJQfSrE",
        "title": "Says",
        "artist": "Nils Frahm",
        "album": "Spaces",
        "duration": 498,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27344beff2f0733508e7284acb3",
        "genre": "Focus",
        "year": 2013,
        "spotifyId": "5626KdflSKfeDK7RJQfSrE",
        "spotifyUrl": "https://open.spotify.com/track/5626KdflSKfeDK7RJQfSrE",
        "spotifyUri": "spotify:track:5626KdflSKfeDK7RJQfSrE"
      },
      {
        "id": "6Xajr512QEGAZ20bqAWkyT",
        "title": "Near Light",
        "artist": "Ólafur Arnalds",
        "album": "Living Room Songs",
        "duration": 209,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273b39434500b17332cd9818487",
        "genre": "Focus",
        "year": 2011,
        "spotifyId": "6Xajr512QEGAZ20bqAWkyT",
        "spotifyUrl": "https://open.spotify.com/track/6Xajr512QEGAZ20bqAWkyT",
        "spotifyUri": "spotify:track:6Xajr512QEGAZ20bqAWkyT"
      },
      {
        "id": "6c7uYlmHJtZPnenPjqG7Ir",
        "title": "Sleeping Lotus",
        "artist": "Joep Beving",
        "album": "Solipsism",
        "duration": 152,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273b61d334e6d7ec597d5cdc38a",
        "genre": "Focus",
        "year": 2015,
        "spotifyId": "6c7uYlmHJtZPnenPjqG7Ir",
        "spotifyUrl": "https://open.spotify.com/track/6c7uYlmHJtZPnenPjqG7Ir",
        "spotifyUri": "spotify:track:6c7uYlmHJtZPnenPjqG7Ir"
      },
      {
        "id": "3Sy6wgTNEp6vSgLs4EyXAf",
        "title": "Flight from the City",
        "artist": "Jóhann Jóhannsson, Yuki Numata Resnick, Tarn Travers, Ben Russell, Clarice Jensen",
        "album": "Orphée",
        "duration": 391,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2738988ae051bcdcab293a76f3d",
        "genre": "Focus",
        "year": 2016,
        "spotifyId": "3Sy6wgTNEp6vSgLs4EyXAf",
        "spotifyUrl": "https://open.spotify.com/track/3Sy6wgTNEp6vSgLs4EyXAf",
        "spotifyUri": "spotify:track:3Sy6wgTNEp6vSgLs4EyXAf"
      }
    ],
    "followersCount": 23565,
    "releaseDate": "2024 Archive",
    "tags": [
      "Focus",
      "Neoclassical",
      "Minimal Piano",
      "Ambient"
    ],
    "spotifyId": "1BncfTJAWxrsxyT9culBrj",
    "spotifyUrl": "https://open.spotify.com/search/Deep%20Focus",
    "spotifyUri": "spotify:search:Deep%20Focus"
  },
  {
    "id": "sunday-morning",
    "title": "Sunday Morning",
    "subtitle": "Gentle acoustic fingerpicking, birdsong, and quiet reflection.",
    "description": "Soft morning light through tall windows. Gentle folk acoustic fingerstyle, gentle whispers, and contemplative morning pace.",
    "curator": "Clara Bennett",
    "curatorRole": "Morning Sound Resident",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5eb968cf402324f61c6b3e34b22",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273e369195caf5d169bf5e9eafc",
    "accentColor": "#282618",
    "category": "discover",
    "tracks": [
      {
        "id": "4KROoGIaPaR1pBHPnR3bwC",
        "title": "Pink Moon",
        "artist": "Nick Drake",
        "album": "Pink Moon",
        "duration": 124,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273e369195caf5d169bf5e9eafc",
        "genre": "Morning",
        "year": 1972,
        "spotifyId": "4KROoGIaPaR1pBHPnR3bwC",
        "spotifyUrl": "https://open.spotify.com/track/4KROoGIaPaR1pBHPnR3bwC",
        "spotifyUri": "spotify:track:4KROoGIaPaR1pBHPnR3bwC"
      },
      {
        "id": "6R8agdKCfA4Poo0vnRKQKo",
        "title": "Cayman Islands",
        "artist": "Kings of Convenience",
        "album": "Riot On An Empty Street",
        "duration": 183,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273e9a18c4792e88f34bd17bbaf",
        "genre": "Morning",
        "year": 2004,
        "spotifyId": "6R8agdKCfA4Poo0vnRKQKo",
        "spotifyUrl": "https://open.spotify.com/track/6R8agdKCfA4Poo0vnRKQKo",
        "spotifyUri": "spotify:track:6R8agdKCfA4Poo0vnRKQKo"
      },
      {
        "id": "5ibNaVO251Pb2c0Wdl00gG",
        "title": "Heartbeats",
        "artist": "José González",
        "album": "Veneer",
        "duration": 160,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27376557bf2d3926bf5a607cd92",
        "genre": "Morning",
        "year": 2003,
        "spotifyId": "5ibNaVO251Pb2c0Wdl00gG",
        "spotifyUrl": "https://open.spotify.com/track/5ibNaVO251Pb2c0Wdl00gG",
        "spotifyUri": "spotify:track:5ibNaVO251Pb2c0Wdl00gG"
      },
      {
        "id": "1fEGtTZjrjJW8eUeewnNJR",
        "title": "Flightless Bird, American Mouth",
        "artist": "Iron & Wine",
        "album": "The Shepherd's Dog",
        "duration": 242,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273816243514f01ac30d0932622",
        "genre": "Morning",
        "year": 2007,
        "spotifyId": "1fEGtTZjrjJW8eUeewnNJR",
        "spotifyUrl": "https://open.spotify.com/track/1fEGtTZjrjJW8eUeewnNJR",
        "spotifyUri": "spotify:track:1fEGtTZjrjJW8eUeewnNJR"
      },
      {
        "id": "5GbVzc6Ex5LYlLJqzRQhuy",
        "title": "Mystery of Love",
        "artist": "Sufjan Stevens",
        "album": "Mystery of Love",
        "duration": 249,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733fc1588803d1887f11d660cc",
        "genre": "Morning",
        "year": 2017,
        "spotifyId": "5GbVzc6Ex5LYlLJqzRQhuy",
        "spotifyUrl": "https://open.spotify.com/track/5GbVzc6Ex5LYlLJqzRQhuy",
        "spotifyUri": "spotify:track:5GbVzc6Ex5LYlLJqzRQhuy"
      },
      {
        "id": "35KiiILklye1JRRctaLUb4",
        "title": "Holocene",
        "artist": "Bon Iver",
        "album": "Bon Iver, Bon Iver",
        "duration": 337,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2734b6b1547455bbecb9f6bba64",
        "genre": "Morning",
        "year": 2011,
        "spotifyId": "35KiiILklye1JRRctaLUb4",
        "spotifyUrl": "https://open.spotify.com/track/35KiiILklye1JRRctaLUb4",
        "spotifyUri": "spotify:track:35KiiILklye1JRRctaLUb4"
      }
    ],
    "followersCount": 21647,
    "releaseDate": "2024 Archive",
    "tags": [
      "Morning",
      "Gentle Folk",
      "Acoustic Guitar",
      "Peaceful"
    ],
    "spotifyId": "4KROoGIaPaR1pBHPnR3bwC",
    "spotifyUrl": "https://open.spotify.com/search/Sunday%20Morning",
    "spotifyUri": "spotify:search:Sunday%20Morning"
  },
  {
    "id": "night-drive",
    "title": "Night Drive",
    "subtitle": "Cinematic synthwave, highway momentum, and retro arpeggios.",
    "description": "Built for empty four-lane highways and neon overhead reflections. Analog synthesizers pushing kinetic rhythm through the darkness.",
    "curator": "Viktor Cruz",
    "curatorRole": "Electronic Director",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5eb2d21a50b86a3449339e879a9",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273d6d8c2eaa1f9031b62f7a3f7",
    "accentColor": "#2b1424",
    "category": "workout",
    "tracks": [
      {
        "id": "0U0ldCRmgCqhVvD6ksG63j",
        "title": "Nightcall",
        "artist": "Kavinsky",
        "album": "Nightcall",
        "duration": 258,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273d6d8c2eaa1f9031b62f7a3f7",
        "genre": "Drive",
        "year": 2010,
        "spotifyId": "0U0ldCRmgCqhVvD6ksG63j",
        "spotifyUrl": "https://open.spotify.com/track/0U0ldCRmgCqhVvD6ksG63j",
        "spotifyUri": "spotify:track:0U0ldCRmgCqhVvD6ksG63j"
      },
      {
        "id": "5BAJDNTutBFJL27pKunac1",
        "title": "Shadow (Maceo Plex Remix)",
        "artist": "Maceo Plex, Chromatics",
        "album": "Shadow (Remixes)",
        "duration": 299,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27369ff053afe6df53a6a1fda92",
        "genre": "Drive",
        "year": 2021,
        "spotifyId": "5BAJDNTutBFJL27pKunac1",
        "spotifyUrl": "https://open.spotify.com/track/5BAJDNTutBFJL27pKunac1",
        "spotifyUri": "spotify:track:5BAJDNTutBFJL27pKunac1"
      },
      {
        "id": "6mB9A9YLbY4jxpKX5EYAnT",
        "title": "Sunset",
        "artist": "The Midnight",
        "album": "Endless Summer",
        "duration": 327,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27366f27b0ef0b92099a1927721",
        "genre": "Drive",
        "year": 2016,
        "spotifyId": "6mB9A9YLbY4jxpKX5EYAnT",
        "spotifyUrl": "https://open.spotify.com/track/6mB9A9YLbY4jxpKX5EYAnT",
        "spotifyUri": "spotify:track:6mB9A9YLbY4jxpKX5EYAnT"
      },
      {
        "id": "6GyFP1nfCDB8lbD2bG0Hq9",
        "title": "Midnight City",
        "artist": "M83",
        "album": "Hurry up, We're Dreaming",
        "duration": 244,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27362100064780b1d919a95fcf4",
        "genre": "Drive",
        "year": 2011,
        "spotifyId": "6GyFP1nfCDB8lbD2bG0Hq9",
        "spotifyUrl": "https://open.spotify.com/track/6GyFP1nfCDB8lbD2bG0Hq9",
        "spotifyUri": "spotify:track:6GyFP1nfCDB8lbD2bG0Hq9"
      },
      {
        "id": "5VKEsChbUowEF2BT0gJSGX",
        "title": "Tech Noir",
        "artist": "Gunship, John Carpenter, Charlie Simpson",
        "album": "GUNSHIP",
        "duration": 297,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ff61b32d8807c35e7dd09aa7",
        "genre": "Drive",
        "year": 2015,
        "spotifyId": "5VKEsChbUowEF2BT0gJSGX",
        "spotifyUrl": "https://open.spotify.com/track/5VKEsChbUowEF2BT0gJSGX",
        "spotifyUri": "spotify:track:5VKEsChbUowEF2BT0gJSGX"
      },
      {
        "id": "2NHkwSwm6C6eAX3z6xm7Uy",
        "title": "Resonance",
        "artist": "Home",
        "album": "Odyssey",
        "duration": 213,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273df1e0c6802ff4723a425179c",
        "genre": "Drive",
        "year": 2014,
        "spotifyId": "2NHkwSwm6C6eAX3z6xm7Uy",
        "spotifyUrl": "https://open.spotify.com/track/2NHkwSwm6C6eAX3z6xm7Uy",
        "spotifyUri": "spotify:track:2NHkwSwm6C6eAX3z6xm7Uy"
      }
    ],
    "followersCount": 15087,
    "releaseDate": "2024 Archive",
    "tags": [
      "Drive",
      "Synthwave",
      "Analog Arps",
      "Highway"
    ],
    "spotifyId": "0U0ldCRmgCqhVvD6ksG63j",
    "spotifyUrl": "https://open.spotify.com/search/Night%20Drive",
    "spotifyUri": "spotify:search:Night%20Drive"
  },
  {
    "id": "tokyo-drift-bass",
    "title": "Tokyo Drift & Sub-Bass",
    "subtitle": "Future garage, 2-step percussion, and subterranean UK low-end.",
    "description": "Heavy damp air, neon reflections on wet asphalt, and pitch-shifted vocal samples over intricate 2-step garage rhythms.",
    "curator": "Kenji Sato",
    "curatorRole": "Garage Selector",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5ebc5211974ef6f6f1400bf1ffb",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2730ea5498497e5bdcdb59a687a",
    "accentColor": "#17142b",
    "category": "late-night",
    "tracks": [
      {
        "id": "5kadOt1O3LrIV46dns9v7u",
        "title": "Archangel",
        "artist": "Burial",
        "album": "Untrue",
        "duration": 240,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2730ea5498497e5bdcdb59a687a",
        "genre": "Future Garage",
        "year": 2007,
        "spotifyId": "5kadOt1O3LrIV46dns9v7u",
        "spotifyUrl": "https://open.spotify.com/track/5kadOt1O3LrIV46dns9v7u",
        "spotifyUri": "spotify:track:5kadOt1O3LrIV46dns9v7u"
      },
      {
        "id": "1YGxSgWIWqxKuLLocPVxhC",
        "title": "So U Kno",
        "artist": "Overmono",
        "album": "Good Lies",
        "duration": 344,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273dd8fbf4e3c304f6b3602a745",
        "genre": "Future Garage",
        "year": 2023,
        "spotifyId": "1YGxSgWIWqxKuLLocPVxhC",
        "spotifyUrl": "https://open.spotify.com/track/1YGxSgWIWqxKuLLocPVxhC",
        "spotifyUri": "spotify:track:1YGxSgWIWqxKuLLocPVxhC"
      },
      {
        "id": "4Z4i631BesV0P6LTvfLAdL",
        "title": "Talk to Me You'll Understand",
        "artist": "Ross from Friends",
        "album": "You'll Understand",
        "duration": 417,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273088d99c85e6de4f30b39679c",
        "genre": "Future Garage",
        "year": 2017,
        "spotifyId": "4Z4i631BesV0P6LTvfLAdL",
        "spotifyUrl": "https://open.spotify.com/track/4Z4i631BesV0P6LTvfLAdL",
        "spotifyUri": "spotify:track:4Z4i631BesV0P6LTvfLAdL"
      },
      {
        "id": "79Jl8KMvmnXedTjjW6pJan",
        "title": "Gosh",
        "artist": "Jamie xx, MC Moose",
        "album": "In Colour",
        "duration": 291,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733b104b3cfcf52e380e90254d",
        "genre": "Future Garage",
        "year": 2015,
        "spotifyId": "79Jl8KMvmnXedTjjW6pJan",
        "spotifyUrl": "https://open.spotify.com/track/79Jl8KMvmnXedTjjW6pJan",
        "spotifyUri": "spotify:track:79Jl8KMvmnXedTjjW6pJan"
      },
      {
        "id": "0uKrhHBDUQ4w5fv4qwOubP",
        "title": "Breathe",
        "artist": "Télépopmusik, Angela McCluskey",
        "album": "Genetic World",
        "duration": 282,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c65b1f9d6ca322de8b85c505",
        "genre": "Future Garage",
        "year": 2001,
        "spotifyId": "0uKrhHBDUQ4w5fv4qwOubP",
        "spotifyUrl": "https://open.spotify.com/track/0uKrhHBDUQ4w5fv4qwOubP",
        "spotifyUri": "spotify:track:0uKrhHBDUQ4w5fv4qwOubP"
      }
    ],
    "followersCount": 16227,
    "releaseDate": "2024 Archive",
    "tags": [
      "Future Garage",
      "Sub Bass",
      "Tokyo",
      "2-Step"
    ],
    "spotifyId": "5kadOt1O3LrIV46dns9v7u",
    "spotifyUrl": "https://open.spotify.com/search/Tokyo%20Drift%20%26%20Sub-Bass",
    "spotifyUri": "spotify:search:Tokyo%20Drift%20%26%20Sub-Bass"
  },
  {
    "id": "nordic-solitude",
    "title": "Nordic Solitude",
    "subtitle": "Sub-zero ambient soundscapes and Scandinavian acoustics.",
    "description": "Reverberant acoustic spaces and frozen electronic drones recorded across Iceland and Scandinavia. Expansive, crystalline, and vast.",
    "curator": "Astrid Lindholm",
    "curatorRole": "Nordic Sound Archivalist",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5eb98165d752c03380061e8bfb8",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2737d5c9fa537845b71c4eb3b5e",
    "accentColor": "#14272b",
    "category": "focus",
    "tracks": [
      {
        "id": "07eGxuz8bL6QMsRqEe1Adu",
        "title": "Svefn-g-englar",
        "artist": "Sigur Rós",
        "album": "Ágætis byrjun",
        "duration": 607,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2737d5c9fa537845b71c4eb3b5e",
        "genre": "Nordic",
        "year": 1999,
        "spotifyId": "07eGxuz8bL6QMsRqEe1Adu",
        "spotifyUrl": "https://open.spotify.com/track/07eGxuz8bL6QMsRqEe1Adu",
        "spotifyUri": "spotify:track:07eGxuz8bL6QMsRqEe1Adu"
      },
      {
        "id": "7iHl6LcHD94l5VpmfrBUmG",
        "title": "Riverside",
        "artist": "Agnes Obel",
        "album": "Philharmonics",
        "duration": 229,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ae70ffe7505b2a4f45372cb5",
        "genre": "Nordic",
        "year": 2010,
        "spotifyId": "7iHl6LcHD94l5VpmfrBUmG",
        "spotifyUrl": "https://open.spotify.com/track/7iHl6LcHD94l5VpmfrBUmG",
        "spotifyUri": "spotify:track:7iHl6LcHD94l5VpmfrBUmG"
      },
      {
        "id": "2bB6iDVgm25WkYv0yBz1BD",
        "title": "Looped",
        "artist": "Kiasmos",
        "album": "Kiasmos",
        "duration": 361,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273bb0ea18476f664df4f9fd460",
        "genre": "Nordic",
        "year": 2014,
        "spotifyId": "2bB6iDVgm25WkYv0yBz1BD",
        "spotifyUrl": "https://open.spotify.com/track/2bB6iDVgm25WkYv0yBz1BD",
        "spotifyUri": "spotify:track:2bB6iDVgm25WkYv0yBz1BD"
      },
      {
        "id": "6XmY3xNVGemozNMApOCobZ",
        "title": "Pastoral",
        "artist": "Christian Löffler",
        "album": "Parallels: Shellac Reworks By Christian Löffler",
        "duration": 221,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2732ae3934450a9b0c4d9e5c3d3",
        "genre": "Nordic",
        "year": 2021,
        "spotifyId": "6XmY3xNVGemozNMApOCobZ",
        "spotifyUrl": "https://open.spotify.com/track/6XmY3xNVGemozNMApOCobZ",
        "spotifyUri": "spotify:track:6XmY3xNVGemozNMApOCobZ"
      },
      {
        "id": "6eTGxxQxiTFE6LfZHC33Wm",
        "title": "Hoppípolla",
        "artist": "Sigur Rós",
        "album": "Takk...",
        "duration": 269,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ddd29279ec01511dca4c441c",
        "genre": "Nordic",
        "year": 2005,
        "spotifyId": "6eTGxxQxiTFE6LfZHC33Wm",
        "spotifyUrl": "https://open.spotify.com/track/6eTGxxQxiTFE6LfZHC33Wm",
        "spotifyUri": "spotify:track:6eTGxxQxiTFE6LfZHC33Wm"
      },
      {
        "id": "2wA8cQwmSw0eVVhOfNRDuZ",
        "title": "The Sun's Gone Dim and the Sky's Turned Black",
        "artist": "Jóhann Jóhannsson",
        "album": "The Sun's Gone Dim and the Sky's Turned Black",
        "duration": 341,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2737cc2afdaef2df15024915675",
        "genre": "Nordic",
        "year": 2006,
        "spotifyId": "2wA8cQwmSw0eVVhOfNRDuZ",
        "spotifyUrl": "https://open.spotify.com/track/2wA8cQwmSw0eVVhOfNRDuZ",
        "spotifyUri": "spotify:track:2wA8cQwmSw0eVVhOfNRDuZ"
      }
    ],
    "followersCount": 12028,
    "releaseDate": "2024 Archive",
    "tags": [
      "Nordic",
      "Glacial Ambient",
      "Iceland",
      "Atmospheric"
    ],
    "spotifyId": "07eGxuz8bL6QMsRqEe1Adu",
    "spotifyUrl": "https://open.spotify.com/search/Nordic%20Solitude",
    "spotifyUri": "spotify:search:Nordic%20Solitude"
  },
  {
    "id": "desert-sun-dust",
    "title": "Desert Sun & Dust",
    "subtitle": "Psychedelic desert guitars, cumbia groove, and warm tape echo.",
    "description": "Warm wind across cracked earth. Sun-baked tremolo guitars, unhurried Latin polyrhythms, and hypnotic cinematic instrumentals.",
    "curator": "Mateo Ortiz",
    "curatorRole": "Global Grooves",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5ebb5d23ee18bb9d68128509ce1",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c0c54c6de30010265e23c840",
    "accentColor": "#2b2314",
    "category": "discover",
    "tracks": [
      {
        "id": "6fjC14MDp2hgMiHNfuiexj",
        "title": "Dorado Valley",
        "artist": "Hermanos Gutiérrez",
        "album": "El Bueno Y El Malo",
        "duration": 207,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c0c54c6de30010265e23c840",
        "genre": "Desert Rock",
        "year": 2022,
        "spotifyId": "6fjC14MDp2hgMiHNfuiexj",
        "spotifyUrl": "https://open.spotify.com/track/6fjC14MDp2hgMiHNfuiexj",
        "spotifyUri": "spotify:track:6fjC14MDp2hgMiHNfuiexj"
      },
      {
        "id": "4H0KLsPpr5atperrHGfz3x",
        "title": "Catamaran",
        "artist": "Allah-Las",
        "album": "Allah-Las",
        "duration": 213,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273db27283ab2ae5eddb265d9a7",
        "genre": "Desert Rock",
        "year": 2012,
        "spotifyId": "4H0KLsPpr5atperrHGfz3x",
        "spotifyUrl": "https://open.spotify.com/track/4H0KLsPpr5atperrHGfz3x",
        "spotifyUri": "spotify:track:4H0KLsPpr5atperrHGfz3x"
      },
      {
        "id": "6galGfTFHHzsPieYkReYyN",
        "title": "Organism",
        "artist": "Tommy Guerrero",
        "album": "Soul Food Taqueria",
        "duration": 248,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273c27b61aaedf74586b118e34a",
        "genre": "Desert Rock",
        "year": 2002,
        "spotifyId": "6galGfTFHHzsPieYkReYyN",
        "spotifyUrl": "https://open.spotify.com/track/6galGfTFHHzsPieYkReYyN",
        "spotifyUri": "spotify:track:6galGfTFHHzsPieYkReYyN"
      },
      {
        "id": "2dXs6WlSVXJX3i99Xw4n2u",
        "title": "Don't Call My Name",
        "artist": "Skinshape",
        "album": "Life & Love",
        "duration": 250,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27355832e9fb94c657e6e94cb2d",
        "genre": "Desert Rock",
        "year": 2017,
        "spotifyId": "2dXs6WlSVXJX3i99Xw4n2u",
        "spotifyUrl": "https://open.spotify.com/track/2dXs6WlSVXJX3i99Xw4n2u",
        "spotifyUri": "spotify:track:2dXs6WlSVXJX3i99Xw4n2u"
      },
      {
        "id": "5EvSpCCDpZOJvFwr4ZWSk0",
        "title": "Maria También",
        "artist": "Khruangbin",
        "album": "Con Todo El Mundo",
        "duration": 191,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273f8bfa2a86764fc18a80d382e",
        "genre": "Desert Rock",
        "year": 2018,
        "spotifyId": "5EvSpCCDpZOJvFwr4ZWSk0",
        "spotifyUrl": "https://open.spotify.com/track/5EvSpCCDpZOJvFwr4ZWSk0",
        "spotifyUri": "spotify:track:5EvSpCCDpZOJvFwr4ZWSk0"
      }
    ],
    "followersCount": 13583,
    "releaseDate": "2024 Archive",
    "tags": [
      "Desert Rock",
      "Cumbia",
      "Tremolo Guitar",
      "Sunlit"
    ],
    "spotifyId": "6fjC14MDp2hgMiHNfuiexj",
    "spotifyUrl": "https://open.spotify.com/search/Desert%20Sun%20%26%20Dust",
    "spotifyUri": "spotify:search:Desert%20Sun%20%26%20Dust"
  },
  {
    "id": "acoustic-solitude",
    "title": "Acoustic Solitude",
    "subtitle": "Stripped solo guitar, room tone, and raw emotional presence.",
    "description": "No production gloss. Just fingers on steel strings, the natural resonance of wooden instruments, and quiet emotional vulnerability.",
    "curator": "Liam Gallagher-Jones",
    "curatorRole": "Acoustic Curator",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5eb0b9a897e416a908990141675",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ea7ac80765aa4549d18a27b9",
    "accentColor": "#231e14",
    "category": "discover",
    "tracks": [
      {
        "id": "52Bg6oaos7twR7IUtEpqcE",
        "title": "Between The Bars",
        "artist": "Elliott Smith",
        "album": "Either/Or",
        "duration": 141,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273ea7ac80765aa4549d18a27b9",
        "genre": "Solo Guitar",
        "year": 1997,
        "spotifyId": "52Bg6oaos7twR7IUtEpqcE",
        "spotifyUrl": "https://open.spotify.com/track/52Bg6oaos7twR7IUtEpqcE",
        "spotifyUri": "spotify:track:52Bg6oaos7twR7IUtEpqcE"
      },
      {
        "id": "5yyRH93h4Pm6tXXYTxt7ea",
        "title": "The Blower's Daughter",
        "artist": "Damien Rice",
        "album": "O",
        "duration": 287,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273fbf054cdb847f4e042d88642",
        "genre": "Solo Guitar",
        "year": 2002,
        "spotifyId": "5yyRH93h4Pm6tXXYTxt7ea",
        "spotifyUrl": "https://open.spotify.com/track/5yyRH93h4Pm6tXXYTxt7ea",
        "spotifyUri": "spotify:track:5yyRH93h4Pm6tXXYTxt7ea"
      },
      {
        "id": "4PwWESSlTwzvw9B7bmtTLS",
        "title": "anything",
        "artist": "Adrianne Lenker",
        "album": "songs",
        "duration": 202,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2738ebe185fc4824bc6e568b511",
        "genre": "Solo Guitar",
        "year": 2020,
        "spotifyId": "4PwWESSlTwzvw9B7bmtTLS",
        "spotifyUrl": "https://open.spotify.com/track/4PwWESSlTwzvw9B7bmtTLS",
        "spotifyUri": "spotify:track:4PwWESSlTwzvw9B7bmtTLS"
      },
      {
        "id": "3B3eOgLJSqPEA0RfboIQVM",
        "title": "Skinny Love",
        "artist": "Bon Iver",
        "album": "For Emma, Forever Ago",
        "duration": 239,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273bf7c317a63c4f128b8823406",
        "genre": "Solo Guitar",
        "year": 2008,
        "spotifyId": "3B3eOgLJSqPEA0RfboIQVM",
        "spotifyUrl": "https://open.spotify.com/track/3B3eOgLJSqPEA0RfboIQVM",
        "spotifyUri": "spotify:track:3B3eOgLJSqPEA0RfboIQVM"
      },
      {
        "id": "5Qnrgqy1pAm9GyNQOgyVFz",
        "title": "Fourth of July",
        "artist": "Sufjan Stevens",
        "album": "Carrie & Lowell",
        "duration": 279,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273820e2ac14772ae3162c6d479",
        "genre": "Solo Guitar",
        "year": 2015,
        "spotifyId": "5Qnrgqy1pAm9GyNQOgyVFz",
        "spotifyUrl": "https://open.spotify.com/track/5Qnrgqy1pAm9GyNQOgyVFz",
        "spotifyUri": "spotify:track:5Qnrgqy1pAm9GyNQOgyVFz"
      },
      {
        "id": "4LGF2tDg3878bs0mQPByZ4",
        "title": "Guaranteed",
        "artist": "Eddie Vedder",
        "album": "Into The Wild (Music For The Motion Picture)",
        "duration": 165,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733ed52339ae78ac1b695e8d80",
        "genre": "Solo Guitar",
        "year": 2007,
        "spotifyId": "4LGF2tDg3878bs0mQPByZ4",
        "spotifyUrl": "https://open.spotify.com/track/4LGF2tDg3878bs0mQPByZ4",
        "spotifyUri": "spotify:track:4LGF2tDg3878bs0mQPByZ4"
      }
    ],
    "followersCount": 15191,
    "releaseDate": "2024 Archive",
    "tags": [
      "Solo Guitar",
      "Room Tone",
      "Intimate",
      "Analog"
    ],
    "spotifyId": "52Bg6oaos7twR7IUtEpqcE",
    "spotifyUrl": "https://open.spotify.com/search/Acoustic%20Solitude",
    "spotifyUri": "spotify:search:Acoustic%20Solitude"
  },
  {
    "id": "analog-synthetics",
    "title": "Analog Synthetics",
    "subtitle": "Modular synthesizer sequences, tape loops, and harmonic distortion.",
    "description": "Dedicated to hardware synthesis: Buchla modular systems, Roland Juno chorus filters, and vintage tape loop decay.",
    "curator": "Dr. Evelyn Reed",
    "curatorRole": "Synthesis Historian",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5ebd5866164223297a78ef40da8",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273cf2e55988066ba69d58245ff",
    "accentColor": "#1f142b",
    "category": "late-night",
    "tracks": [
      {
        "id": "0vp09QgBhShrQOL2w7P8k4",
        "title": "Recovery",
        "artist": "Rival Consoles",
        "album": "Odyssey / Sonne",
        "duration": 290,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273cf2e55988066ba69d58245ff",
        "genre": "Modular Synth",
        "year": 2015,
        "spotifyId": "0vp09QgBhShrQOL2w7P8k4",
        "spotifyUrl": "https://open.spotify.com/track/0vp09QgBhShrQOL2w7P8k4",
        "spotifyUri": "spotify:track:0vp09QgBhShrQOL2w7P8k4"
      },
      {
        "id": "75QdM3nsnAluOD19G1J4il",
        "title": "Bias",
        "artist": "Floating Points",
        "album": "Crush",
        "duration": 308,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273216a393a7606aa7de52c4636",
        "genre": "Modular Synth",
        "year": 2019,
        "spotifyId": "75QdM3nsnAluOD19G1J4il",
        "spotifyUrl": "https://open.spotify.com/track/75QdM3nsnAluOD19G1J4il",
        "spotifyUri": "spotify:track:75QdM3nsnAluOD19G1J4il"
      },
      {
        "id": "2ZIaH69kaz55RM4Pjx6KXl",
        "title": "Two Thousand and Seventeen",
        "artist": "Four Tet",
        "album": "New Energy",
        "duration": 252,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2733f31769b727102837cb32a63",
        "genre": "Modular Synth",
        "year": 2017,
        "spotifyId": "2ZIaH69kaz55RM4Pjx6KXl",
        "spotifyUrl": "https://open.spotify.com/track/2ZIaH69kaz55RM4Pjx6KXl",
        "spotifyUri": "spotify:track:2ZIaH69kaz55RM4Pjx6KXl"
      }
    ],
    "followersCount": 17686,
    "releaseDate": "2024 Archive",
    "tags": [
      "Modular Synth",
      "Hardware",
      "Buchla",
      "Tape Loops"
    ],
    "spotifyId": "0vp09QgBhShrQOL2w7P8k4",
    "spotifyUrl": "https://open.spotify.com/search/Analog%20Synthetics",
    "spotifyUri": "spotify:search:Analog%20Synthetics"
  },
  {
    "id": "permanent-archive",
    "title": "Permanent Archive",
    "subtitle": "Seminal masterpieces of ambient and leftfield electronic music.",
    "description": "The foundation stones of nocturnal music history. Timeless records that defined modern ambient, trip-hop, and intelligent dance music.",
    "curator": "LIVO Historical Board",
    "curatorRole": "Archival Board",
    "curatorAvatar": "https://i.scdn.co/image/ab6761610000e5eb98165d752c03380061e8bfb8",
    "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27337a379ca6520eaf191de6ff2",
    "accentColor": "#1a1a1a",
    "category": "classics",
    "tracks": [
      {
        "id": "3bCmDqflFBHijgJfvtqev5",
        "title": "1/1 - Remastered 2004",
        "artist": "Brian Eno",
        "album": "Ambient 1: Music For Airports (Remastered 2004)",
        "duration": 1042,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b27337a379ca6520eaf191de6ff2",
        "genre": "Masterpieces",
        "year": 1978,
        "spotifyId": "3bCmDqflFBHijgJfvtqev5",
        "spotifyUrl": "https://open.spotify.com/track/3bCmDqflFBHijgJfvtqev5",
        "spotifyUri": "spotify:track:3bCmDqflFBHijgJfvtqev5"
      },
      {
        "id": "1uaGSDFsLdReQgg8p7Obwh",
        "title": "Avril 14th",
        "artist": "Aphex Twin",
        "album": "Drukqs",
        "duration": 126,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2732f175ac7dee768cefd14a01c",
        "genre": "Masterpieces",
        "year": 2001,
        "spotifyId": "1uaGSDFsLdReQgg8p7Obwh",
        "spotifyUrl": "https://open.spotify.com/track/1uaGSDFsLdReQgg8p7Obwh",
        "spotifyUri": "spotify:track:1uaGSDFsLdReQgg8p7Obwh"
      },
      {
        "id": "5Hf2h59YLInKlic7ooWZVd",
        "title": "Roygbiv",
        "artist": "Boards of Canada",
        "album": "Music Has The Right To Children",
        "duration": 149,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2739effb26eea559ce6f3fed751",
        "genre": "Masterpieces",
        "year": 1998,
        "spotifyId": "5Hf2h59YLInKlic7ooWZVd",
        "spotifyUrl": "https://open.spotify.com/track/5Hf2h59YLInKlic7ooWZVd",
        "spotifyUri": "spotify:track:5Hf2h59YLInKlic7ooWZVd"
      },
      {
        "id": "67Hna13dNDkZvBpTXRIaOJ",
        "title": "Teardrop",
        "artist": "Massive Attack, Elizabeth Fraser",
        "album": "Mezzanine",
        "duration": 331,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b2732fcb0a3c7a66e516b11cd26e",
        "genre": "Masterpieces",
        "year": 1998,
        "spotifyId": "67Hna13dNDkZvBpTXRIaOJ",
        "spotifyUrl": "https://open.spotify.com/track/67Hna13dNDkZvBpTXRIaOJ",
        "spotifyUri": "spotify:track:67Hna13dNDkZvBpTXRIaOJ"
      },
      {
        "id": "3Ty7OTBNSigGEpeW2PqcsC",
        "title": "Glory Box",
        "artist": "Portishead",
        "album": "Dummy",
        "duration": 309,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273dc20397b139223620af148f6",
        "genre": "Masterpieces",
        "year": 1994,
        "spotifyId": "3Ty7OTBNSigGEpeW2PqcsC",
        "spotifyUrl": "https://open.spotify.com/track/3Ty7OTBNSigGEpeW2PqcsC",
        "spotifyUri": "spotify:track:3Ty7OTBNSigGEpeW2PqcsC"
      },
      {
        "id": "409z4jUHpq7eIkg3N3FzZh",
        "title": "Windowlicker",
        "artist": "Aphex Twin",
        "album": "Windowlicker",
        "duration": 366,
        "audioUrl": "",
        "artworkUrl": "https://i.scdn.co/image/ab67616d0000b273478bfd5562acad46103b858a",
        "genre": "Masterpieces",
        "year": 1999,
        "spotifyId": "409z4jUHpq7eIkg3N3FzZh",
        "spotifyUrl": "https://open.spotify.com/track/409z4jUHpq7eIkg3N3FzZh",
        "spotifyUri": "spotify:track:409z4jUHpq7eIkg3N3FzZh"
      }
    ],
    "followersCount": 23893,
    "releaseDate": "2024 Archive",
    "tags": [
      "Masterpieces",
      "Ambient Classics",
      "Historical",
      "Pioneers"
    ],
    "spotifyId": "3bCmDqflFBHijgJfvtqev5",
    "spotifyUrl": "https://open.spotify.com/search/Permanent%20Archive",
    "spotifyUri": "spotify:search:Permanent%20Archive"
  }
];

export const SPOTIFY_ARTISTS: Artist[] = [
  {
    id: "tycho",
    name: "Tycho",
    role: "Ambient Electronic Composer",
    bio: "Scott Hansen produces warm, sunlit downtempo textures blending analog synthesizers and organic percussion.",
    image: "https://i.scdn.co/image/ab6761610000e5eb5f33a8c66a4f7e53f19e3498",
    monthlyListeners: 1420000,
    genres: ["Downtempo", "Chillwave", "Ambient Electronic"],
    popularTracks: SPOTIFY_TRACKS.slice(0, 3),
  },
  {
    id: "bonobo",
    name: "Bonobo",
    role: "Electronic Producer & DJ",
    bio: "Simon Green crafting layered, acoustic-electronic world arrangements and subtle breakbeat percussion.",
    image: "https://i.scdn.co/image/ab6761610000e5eb3da1f6d3f232adcf33d8383c",
    monthlyListeners: 2850000,
    genres: ["Trip-Hop", "Downtempo", "Leftfield Bass"],
    popularTracks: SPOTIFY_TRACKS.slice(1, 4),
  },
  {
    id: "bicep",
    name: "Bicep",
    role: "Electronic Duo",
    bio: "Belfast-born duo synthesizing 90s rave nostalgia, melodic techno, and anthemic euphoric synth leads.",
    image: "https://i.scdn.co/image/ab6761610000e5ebcbba45ec77df83c9ae77c28f",
    monthlyListeners: 2100000,
    genres: ["Melodic Techno", "Breakbeat", "Electronic"],
    popularTracks: SPOTIFY_TRACKS.slice(2, 5),
  },
  {
    id: "khruangbin",
    name: "Khruangbin",
    role: "Psychedelic Trio",
    bio: "Houston trio combining Thai funk, surf rock, dub basslines, and Middle Eastern melodies into hypnotic grooves.",
    image: "https://i.scdn.co/image/ab6761610000e5eb09337582ae43dbca74c6e9ba",
    monthlyListeners: 4100000,
    genres: ["Psychedelic Funk", "Dub", "Global Groove"],
    popularTracks: SPOTIFY_TRACKS.slice(6, 9),
  },
  {
    id: "max-richter",
    name: "Max Richter",
    role: "Neoclassical Composer",
    bio: "British-German composer celebrated for minimalist post-classical masterpieces, film scores, and ambient compositions.",
    image: "https://i.scdn.co/image/ab6761610000e5eb4cf2106eb7cfda5943265eb6",
    monthlyListeners: 3900000,
    genres: ["Post-Classical", "Minimalism", "Soundtrack"],
    popularTracks: SPOTIFY_TRACKS.slice(18, 21),
  },
  {
    id: "frank-ocean",
    name: "Frank Ocean",
    role: "Vocalist & Visionary",
    bio: "Acclaimed singer-songwriter known for introspective lyrics, unconventional song structures, and nocturnal soul.",
    image: "https://i.scdn.co/image/ab6761610000e5ebd76ddb487b3fc4abec1e550e",
    monthlyListeners: 32000000,
    genres: ["Alternative R&B", "Neo-Soul", "Art Pop"],
    popularTracks: SPOTIFY_TRACKS.slice(12, 15),
  },
];
